spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    username: smoke
    password: smoke
    url: jdbc:mysql://47.94.96.214:3306/smoke_qz?useUnicode=true&characterEncoding=UTF-8&serverTimezone=GMT%2b8

server:
  port: 8081

#swagger的api文档访问地址
#swagger-ui.html
springfox.documentation.swagger.v2.path: /api-docs

mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl


